// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcwwjytntwbjqppcekda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjd3dqeXRudHdianFwcGNla2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMDY1MTAsImV4cCI6MjA4ODU4MjUxMH0.FPRP7RzUvWBqKYPNlqEk2RFjxzcN5VbcOyWFC93xCzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});